# this file just imports all the modules
# for the conveneience of people using the
# pad, i prefer to grab the invididual
# modules as i need them to not have a bunch
# of stuff i don't need in ram

# `colorlists.ua` is left out bc it's kinda
# big and ime it lags the pad on old hardware
# when it's loaded

~ "mod/card" ~ Card
~ "mod/colors" ~ Colors
~ "mod/fun" ~ Fun
~ "mod/pona" ~ Pona
~ "mod/seximal" ~ Seximal
~ "mod/time" ~ Time