# this file just imports all the modules
# for the conveneience of people using the
# pad, i prefer to grab the invididual
# modules as i need them to not have a bunch
# of extra stuff i don't need on hand

# `colorlists.ua` is left out bc it's kinda
# big and ime it lags the pad on old hardware
# when it's loaded

~ "mod/card" ~ Card
~ "mod/dice" ~ Dice
~ "mod/colors" ~ Colors ExtraPride Unpride
~ "mod/fun" ~ Fun
~ "mod/plt" ~ PltUiua
~ "mod/pona" ~ Pona
~ "mod/seximal" ~ Seximal
~ "mod/time" ~ Time
