# this file exists for testing the modules
# you probably don't need it unless you're
# making a pr to add a module or smth idk
# i'm not good with git lol

~ "mod/card.ua" ~ Card
~ "mod/colors.ua" ~ Unpride
~ "mod/fun.ua" ~ Fun
~ "mod/pona.ua" ~ Pona
~ "mod/seximal.ua" ~ Seximal

# Seximal: get the name of a
# random int less than unexian
°□ Seximal.FourDigitName⚂₁₂₉₆

# Fun: print an rtasn flag and put
# it under the thing above me
▽₂50 ¤Unpride.Rtasn
Fun.ThisMacroDoesNothing!Fun.NeedlesslyComplexFlip

# Cards: pretty-print a hand of five
# and determine if it's a flush
≡₂/$"_ _" ⊃(≡Card.PrintCard|Card.Flush) ↙₅°⍆ Card.Deck

# Pona: write a random int less than
# 10,000 in nasin nanpa pona
⊸°Pona.ParseNNP⚂₁₀₀₀₀
