# Fun library by mun Nanseki
# this library will never be useful

# WARNING: do not take anything in this module seriously
┌─╴Fun
  ┌─╴Sort
    # BOGOSORTTTTT
    # array ? array
    Bogosort ← |1 ⍢(°⍆|¬≍⊸⍆)

    # wait for cosmic rays to flip enough bits in
    # memory to sort the list
    MiracleSort ← |1 ⌅(
      ⍢(∘|¬≍⊸⍆)
    | ⍢(∘|¬≍⊸°⍆)
    )
  └─╴
  # bacdi but objectively worse
  # Deprecated! This joke barely makes sense anymore
  # ment argu ? argu ment
  NeedlesslyComplexFlip ← |2.2 °□⊙°□⊃(⊡0|⊡1)⇌{⊙∘}

  # EMPTY THE STACK AND DIE
  # ? everything
  # Track caller!
  No ← ⍢◌1 # |∞.0

  # it just does nothing
  ThisMacroDoesNothing! ← ^

  # if anyone remembers which xkcd
  # this joke is from please lmk
  RNG ← 4
└─╴
