# the uiua pallete
┌─╴PltUiua
  Text       ← 0.82_0.855_0.925  # color of normal text
  Comment    ← 0.533_0.533_0.533 # color of comments
  Background ← 0.144_0.173_0.227 # color of the editor's background

  LitNum  ← 0.941_0.502_0.314 # color of number literals
  LitChar ← 0.125_0.976_0.988 # color of character literals

  Noad   ← 0.929_0.369_0.416 # color of noadic functions  
  Monad  ← 0.584_0.82_0.416  # color of monadic functions
  Dyad   ← 0.329_0.69_0.988  # color of dyadic functions
  Triad  ← 0.502_0.471_0.945 # color of triadic functions
  Tetrad ← 0.961_0.565_0.784 # color of tetradic functions

  MonadM ← 0.941_0.765_0.435 # color of monadic modifiers
  DyadM  ← 0.8_0.42_0.914    # color of dyadic modifiers
  TriadM ← 0.251_0.941_0.627 # color of triadic modfifiers

  Text⌞       ← 0.2_0.267_0.267   # color of normal text in light mode
  LitChar⌞    ← 0.067_0.8_0.6     # color of character literals in light mode
  Background⌞ ← 0.957_0.965_0.965 # color of the editor's background in light mode
└─╴
